sudo: false
language: python
python: 2.7

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.17

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install mock==1.0.1

script: python setup.py test
